apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-container
        image: myregistrydemo.azurecr.io/flaskapp:v1
        ports:
        - containerPort: 5000
        env:
        - name: ENV_VAR_1
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: ENV_VAR_1
        - name: ENV_VAR_2
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: ENV_VAR_2
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
