name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: az acr login --name myregistrydemo

      - name: Build and Push Docker image
        run: |
          docker build -t myregistry.azurecr.io/flaskapp:${{ github.sha }} .
          docker push myregistry.azurecr.io/flaskapp:${{ github.sha }}

      - name: Set AKS Context
        run: az aks get-credentials --resource-group myRG --name myAKSCluster --overwrite-existing

      - name: Deploy to AKS
        run: |
          kubectl set image deployment/flask-deployment flask-container=myregistry.azurecr.io/flaskapp:${{ github.sha }}
